spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amigos_jwt
    username: root
    password: 1234
    drive-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
